export {default as logoBelmonteWhite} from './logo-white-belmonte.webp'
export {default as Home1} from './home-1.webp'
export {default as Home2} from './home-2.png'

export {default as DuomoProduct} from './duomo-product.webp'
export {default as VeronaProduct} from './verona-product.webp'
export {default as PantheonProduct} from './pantheon-product.webp'
export {default as LasagnaProduct} from './lasagna-product.webp'
export {default as FetucciniProduct} from './fetuccini-product.webp'
export {default as FusilliProduct} from './fussili-product.webp'
export {default as RavioliProduct} from './ravioli-product.webp'
export {default as TotebagProduct} from './totebag-product.webp'